replicaCount: 1

image:
  repository: ghcr.io/chayalyes/devops-homelab-stack
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  host: myapp.local
