replicaCount: 1

image:
  repository: ghcr.io/chayalyes/devops-homelab-stack
  tag: "9cffa51eca53c743eade104f7b355e137773442a"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  host: myapp.local
