replicaCount: 1

image:
  repository: ghcr.io/chayalyes/devops-homelab-stack
  tag: "6050c3deed544d391fca9945927bb1ca76e485c7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  host: myapp.local
